// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    LoginScreen: typeof import('./src/components/LoginScreen.vue')['default']
    MainNav: typeof import('./src/components/MainNav.vue')['default']
    MedicineForm: typeof import('./src/components/medicine/MedicineForm.vue')['default']
    MedicinesList: typeof import('./src/components/medicine/MedicinesList.vue')['default']
    PatientsAddForm: typeof import('./src/components/patients/PatientsAddForm.vue')['default']
    PatientsComponent: typeof import('./src/components/patients/PatientsComponent.vue')['default']
    PatientsTable: typeof import('./src/components/patients/PatientsTable.vue')['default']
    PrescriptionPDFTemplate: typeof import('./src/components/prescriptions/PrescriptionPDFTemplate.vue')['default']
    PrescriptionTable: typeof import('./src/components/prescriptions/PrescriptionTable.vue')['default']
    PrescriptionTableFilters: typeof import('./src/components/prescriptions/PrescriptionTableFilters.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VademecumAddForm: typeof import('./src/components/vademecum/VademecumAddForm.vue')['default']
    VademecumTable: typeof import('./src/components/vademecum/VademecumTable.vue')['default']
  }
}
